### PR TITLE
fix(thermostat): Do not loop state back to homeassistant

### LINKED ISSUE #216: thermostat: Too many pending tasks in queue ' + key
Found alpha 43 matter hub daemon stopped this morning. Saw this in log during the night:

```
[ 2024-11-29T01:20:51.002Z ] [ ERROR ] [ Matter / Logger                                    ]: Unhandled error detected: Too many pending tasks in queue climate.thermostat_salon
  at AsyncLock.acquire (/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/async-lock/lib/index.js:197:15)
  at BridgeDeviceManager.updateEntity (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2436:16)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2421:48
  at Array.map (<anonymous>)
  at BridgeDeviceManager.updateEntities (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2421:28)
  at Object.setState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/home-assistant-js-websocket/dist/store.js:19:32)
  at processEvent (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2258:9)
  at conn.subscribeMessage.type [as callback] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2265:40)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/home-assistant-js-websocket/dist/connection.js:23:34
  at Array.forEach (<anonymous>)
/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/async-lock/lib/index.js:197
		done(false, new Error('Too many pending tasks in queue ' + key));
		            ^
Error: Too many pending tasks in queue climate.thermostat_salon
    at AsyncLock.acquire (/usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/async-lock/lib/index.js:197:15)
    at BridgeDeviceManager.updateEntity (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2436:16)
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2421:48
    at Array.map (<anonymous>)
    at BridgeDeviceManager.updateEntities (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2421:28)
    at Object.setState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/home-assistant-js-websocket/dist/store.js:19:32)
    at processEvent (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2258:9)
    at conn.subscribeMessage.type [as callback] (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2265:40)
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/node_modules/home-assistant-js-websocket/dist/connection.js:23:34
    at Array.forEach (<anonymous>)
Node.js v18.20.4
```

### PR DESCRIPTION
**Pull request by kennylevinsen**
The state change came from homeassistant and so we do not need to tell homeassistant about it.

Fixes #216

### CODE REVIEW

**Comment by t0bst4r** [comment]
I get that point with the deadlock.

But how do we react to changes on the system mode then?
If the thermostat is off, you won't be able to turn it on etc.

**Comment by kennylevinsen** [comment]
Hmm. I suppose the matter client would also write these attributes to directly set the setpoint rather than using the setpointRaiseLower command? Still trying to get my bearings on matter and the codebase.

**Comment by t0bst4r** [comment]
Where you able to test it locally before?

Just copy the `.env.sample` to `.env` and fill the values. Then run `npm run serve`.

The UI is then served on port `localhost:5173`. The backend is running on port 8482, but is proxied by the frontend dev server. So just open up `localhost:5173` in the browser.

Frontend automatically updates on changes. And backend automatically restarts on changes.

**Comment by kennylevinsen** [comment]
Yeah I do have a local debug setup, but I must admit that I have been feeling my way around a bit. :P

This PR is completely borked, closing!

**Pull request closed without merging**
